// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: game/footsies_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from game/footsies_service.proto</summary>
public static partial class FootsiesServiceReflection {

  #region Descriptor
  /// <summary>File descriptor for game/footsies_service.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static FootsiesServiceReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChtnYW1lL2Zvb3RzaWVzX3NlcnZpY2UucHJvdG8aG2dhbWUvY3NoYXJwX25h",
          "bWVzcGFjZS5wcm90byJCCglTdGVwSW5wdXQSEQoJcDBfYWN0aW9uGAEgASgE",
          "EhEKCXAxX2FjdGlvbhgCIAEoBBIPCgduRnJhbWVzGAMgASgEIo4DCgtQbGF5",
          "ZXJTdGF0ZRIXCg9wbGF5ZXJfcG9zaXRpb24YASADKAQSDwoHaXNfZGVhZBgC",
          "IAEoCBIUCgx2aXRhbF9oZWFsdGgYAyABKAQSFAoMZ3VhcmRfaGVhbHRoGAQg",
          "ASgEEhkKEWN1cnJlbnRfYWN0aW9uX2lkGAUgASgEEhwKFGN1cnJlbnRfYWN0",
          "aW9uX2ZyYW1lGAYgASgEEiIKGmN1cnJlbnRfYWN0aW9uX2ZyYW1lX2NvdW50",
          "GAcgASgEEhUKDWlzX2FjdGlvbl9lbmQYCCABKAgSHAoUaXNfYWx3YXlzX2Nh",
          "bmNlbGFibGUYCSABKAgSIAoYY3VycmVudF9hY3Rpb25faGl0X2NvdW50GAog",
          "ASgEEh4KFmN1cnJlbnRfaGl0X3N0dW5fZnJhbWUYCyABKAQSFgoOaXNfaW5f",
          "aGl0X3N0dW4YDCABKAgSHQoVc3ByaXRlX3NoYWtlX3Bvc2l0aW9uGA0gASgE",
          "Eh4KFm1heF9zcHJpdGVfc2hha2VfZnJhbWUYDiABKAQiXQoJR2FtZVN0YXRl",
          "Eh0KB3BsYXllcjAYASABKAsyDC5QbGF5ZXJTdGF0ZRIdCgdwbGF5ZXIxGAIg",
          "ASgLMgwuUGxheWVyU3RhdGUSEgoKdGVybWluYXRlZBgDIAEoCCIHCgVFbXB0",
          "eTKWAQoTRm9vdHNpZXNHYW1lU2VydmljZRIbCglTdGFydEdhbWUSBi5FbXB0",
          "eRoGLkVtcHR5EhsKCVJlc2V0R2FtZRIGLkVtcHR5GgYuRW1wdHkSJQoLU3Rl",
          "cE5GcmFtZXMSCi5TdGVwSW5wdXQaCi5HYW1lU3RhdGUSHgoIR2V0U3RhdGUS",
          "Bi5FbXB0eRoKLkdhbWVTdGF0ZUIMirUYCEZvb3RzaWVzYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.CsharpNamespaceReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::StepInput), global::StepInput.Parser, new[]{ "P0Action", "P1Action", "NFrames" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PlayerState), global::PlayerState.Parser, new[]{ "PlayerPosition", "IsDead", "VitalHealth", "GuardHealth", "CurrentActionId", "CurrentActionFrame", "CurrentActionFrameCount", "IsActionEnd", "IsAlwaysCancelable", "CurrentActionHitCount", "CurrentHitStunFrame", "IsInHitStun", "SpriteShakePosition", "MaxSpriteShakeFrame" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::GameState), global::GameState.Parser, new[]{ "Player0", "Player1", "Terminated" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Empty), global::Empty.Parser, null, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class StepInput : pb::IMessage<StepInput>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<StepInput> _parser = new pb::MessageParser<StepInput>(() => new StepInput());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<StepInput> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FootsiesServiceReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public StepInput() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public StepInput(StepInput other) : this() {
    p0Action_ = other.p0Action_;
    p1Action_ = other.p1Action_;
    nFrames_ = other.nFrames_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public StepInput Clone() {
    return new StepInput(this);
  }

  /// <summary>Field number for the "p0_action" field.</summary>
  public const int P0ActionFieldNumber = 1;
  private ulong p0Action_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong P0Action {
    get { return p0Action_; }
    set {
      p0Action_ = value;
    }
  }

  /// <summary>Field number for the "p1_action" field.</summary>
  public const int P1ActionFieldNumber = 2;
  private ulong p1Action_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong P1Action {
    get { return p1Action_; }
    set {
      p1Action_ = value;
    }
  }

  /// <summary>Field number for the "nFrames" field.</summary>
  public const int NFramesFieldNumber = 3;
  private ulong nFrames_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong NFrames {
    get { return nFrames_; }
    set {
      nFrames_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as StepInput);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(StepInput other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (P0Action != other.P0Action) return false;
    if (P1Action != other.P1Action) return false;
    if (NFrames != other.NFrames) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (P0Action != 0UL) hash ^= P0Action.GetHashCode();
    if (P1Action != 0UL) hash ^= P1Action.GetHashCode();
    if (NFrames != 0UL) hash ^= NFrames.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (P0Action != 0UL) {
      output.WriteRawTag(8);
      output.WriteUInt64(P0Action);
    }
    if (P1Action != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(P1Action);
    }
    if (NFrames != 0UL) {
      output.WriteRawTag(24);
      output.WriteUInt64(NFrames);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (P0Action != 0UL) {
      output.WriteRawTag(8);
      output.WriteUInt64(P0Action);
    }
    if (P1Action != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(P1Action);
    }
    if (NFrames != 0UL) {
      output.WriteRawTag(24);
      output.WriteUInt64(NFrames);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (P0Action != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(P0Action);
    }
    if (P1Action != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(P1Action);
    }
    if (NFrames != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(NFrames);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(StepInput other) {
    if (other == null) {
      return;
    }
    if (other.P0Action != 0UL) {
      P0Action = other.P0Action;
    }
    if (other.P1Action != 0UL) {
      P1Action = other.P1Action;
    }
    if (other.NFrames != 0UL) {
      NFrames = other.NFrames;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          P0Action = input.ReadUInt64();
          break;
        }
        case 16: {
          P1Action = input.ReadUInt64();
          break;
        }
        case 24: {
          NFrames = input.ReadUInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          P0Action = input.ReadUInt64();
          break;
        }
        case 16: {
          P1Action = input.ReadUInt64();
          break;
        }
        case 24: {
          NFrames = input.ReadUInt64();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class PlayerState : pb::IMessage<PlayerState>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PlayerState> _parser = new pb::MessageParser<PlayerState>(() => new PlayerState());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PlayerState> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FootsiesServiceReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerState() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerState(PlayerState other) : this() {
    playerPosition_ = other.playerPosition_.Clone();
    isDead_ = other.isDead_;
    vitalHealth_ = other.vitalHealth_;
    guardHealth_ = other.guardHealth_;
    currentActionId_ = other.currentActionId_;
    currentActionFrame_ = other.currentActionFrame_;
    currentActionFrameCount_ = other.currentActionFrameCount_;
    isActionEnd_ = other.isActionEnd_;
    isAlwaysCancelable_ = other.isAlwaysCancelable_;
    currentActionHitCount_ = other.currentActionHitCount_;
    currentHitStunFrame_ = other.currentHitStunFrame_;
    isInHitStun_ = other.isInHitStun_;
    spriteShakePosition_ = other.spriteShakePosition_;
    maxSpriteShakeFrame_ = other.maxSpriteShakeFrame_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerState Clone() {
    return new PlayerState(this);
  }

  /// <summary>Field number for the "player_position" field.</summary>
  public const int PlayerPositionFieldNumber = 1;
  private static readonly pb::FieldCodec<ulong> _repeated_playerPosition_codec
      = pb::FieldCodec.ForUInt64(10);
  private readonly pbc::RepeatedField<ulong> playerPosition_ = new pbc::RepeatedField<ulong>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<ulong> PlayerPosition {
    get { return playerPosition_; }
  }

  /// <summary>Field number for the "is_dead" field.</summary>
  public const int IsDeadFieldNumber = 2;
  private bool isDead_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsDead {
    get { return isDead_; }
    set {
      isDead_ = value;
    }
  }

  /// <summary>Field number for the "vital_health" field.</summary>
  public const int VitalHealthFieldNumber = 3;
  private ulong vitalHealth_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong VitalHealth {
    get { return vitalHealth_; }
    set {
      vitalHealth_ = value;
    }
  }

  /// <summary>Field number for the "guard_health" field.</summary>
  public const int GuardHealthFieldNumber = 4;
  private ulong guardHealth_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong GuardHealth {
    get { return guardHealth_; }
    set {
      guardHealth_ = value;
    }
  }

  /// <summary>Field number for the "current_action_id" field.</summary>
  public const int CurrentActionIdFieldNumber = 5;
  private ulong currentActionId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong CurrentActionId {
    get { return currentActionId_; }
    set {
      currentActionId_ = value;
    }
  }

  /// <summary>Field number for the "current_action_frame" field.</summary>
  public const int CurrentActionFrameFieldNumber = 6;
  private ulong currentActionFrame_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong CurrentActionFrame {
    get { return currentActionFrame_; }
    set {
      currentActionFrame_ = value;
    }
  }

  /// <summary>Field number for the "current_action_frame_count" field.</summary>
  public const int CurrentActionFrameCountFieldNumber = 7;
  private ulong currentActionFrameCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong CurrentActionFrameCount {
    get { return currentActionFrameCount_; }
    set {
      currentActionFrameCount_ = value;
    }
  }

  /// <summary>Field number for the "is_action_end" field.</summary>
  public const int IsActionEndFieldNumber = 8;
  private bool isActionEnd_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsActionEnd {
    get { return isActionEnd_; }
    set {
      isActionEnd_ = value;
    }
  }

  /// <summary>Field number for the "is_always_cancelable" field.</summary>
  public const int IsAlwaysCancelableFieldNumber = 9;
  private bool isAlwaysCancelable_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsAlwaysCancelable {
    get { return isAlwaysCancelable_; }
    set {
      isAlwaysCancelable_ = value;
    }
  }

  /// <summary>Field number for the "current_action_hit_count" field.</summary>
  public const int CurrentActionHitCountFieldNumber = 10;
  private ulong currentActionHitCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong CurrentActionHitCount {
    get { return currentActionHitCount_; }
    set {
      currentActionHitCount_ = value;
    }
  }

  /// <summary>Field number for the "current_hit_stun_frame" field.</summary>
  public const int CurrentHitStunFrameFieldNumber = 11;
  private ulong currentHitStunFrame_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong CurrentHitStunFrame {
    get { return currentHitStunFrame_; }
    set {
      currentHitStunFrame_ = value;
    }
  }

  /// <summary>Field number for the "is_in_hit_stun" field.</summary>
  public const int IsInHitStunFieldNumber = 12;
  private bool isInHitStun_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsInHitStun {
    get { return isInHitStun_; }
    set {
      isInHitStun_ = value;
    }
  }

  /// <summary>Field number for the "sprite_shake_position" field.</summary>
  public const int SpriteShakePositionFieldNumber = 13;
  private ulong spriteShakePosition_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong SpriteShakePosition {
    get { return spriteShakePosition_; }
    set {
      spriteShakePosition_ = value;
    }
  }

  /// <summary>Field number for the "max_sprite_shake_frame" field.</summary>
  public const int MaxSpriteShakeFrameFieldNumber = 14;
  private ulong maxSpriteShakeFrame_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong MaxSpriteShakeFrame {
    get { return maxSpriteShakeFrame_; }
    set {
      maxSpriteShakeFrame_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PlayerState);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PlayerState other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!playerPosition_.Equals(other.playerPosition_)) return false;
    if (IsDead != other.IsDead) return false;
    if (VitalHealth != other.VitalHealth) return false;
    if (GuardHealth != other.GuardHealth) return false;
    if (CurrentActionId != other.CurrentActionId) return false;
    if (CurrentActionFrame != other.CurrentActionFrame) return false;
    if (CurrentActionFrameCount != other.CurrentActionFrameCount) return false;
    if (IsActionEnd != other.IsActionEnd) return false;
    if (IsAlwaysCancelable != other.IsAlwaysCancelable) return false;
    if (CurrentActionHitCount != other.CurrentActionHitCount) return false;
    if (CurrentHitStunFrame != other.CurrentHitStunFrame) return false;
    if (IsInHitStun != other.IsInHitStun) return false;
    if (SpriteShakePosition != other.SpriteShakePosition) return false;
    if (MaxSpriteShakeFrame != other.MaxSpriteShakeFrame) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= playerPosition_.GetHashCode();
    if (IsDead != false) hash ^= IsDead.GetHashCode();
    if (VitalHealth != 0UL) hash ^= VitalHealth.GetHashCode();
    if (GuardHealth != 0UL) hash ^= GuardHealth.GetHashCode();
    if (CurrentActionId != 0UL) hash ^= CurrentActionId.GetHashCode();
    if (CurrentActionFrame != 0UL) hash ^= CurrentActionFrame.GetHashCode();
    if (CurrentActionFrameCount != 0UL) hash ^= CurrentActionFrameCount.GetHashCode();
    if (IsActionEnd != false) hash ^= IsActionEnd.GetHashCode();
    if (IsAlwaysCancelable != false) hash ^= IsAlwaysCancelable.GetHashCode();
    if (CurrentActionHitCount != 0UL) hash ^= CurrentActionHitCount.GetHashCode();
    if (CurrentHitStunFrame != 0UL) hash ^= CurrentHitStunFrame.GetHashCode();
    if (IsInHitStun != false) hash ^= IsInHitStun.GetHashCode();
    if (SpriteShakePosition != 0UL) hash ^= SpriteShakePosition.GetHashCode();
    if (MaxSpriteShakeFrame != 0UL) hash ^= MaxSpriteShakeFrame.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    playerPosition_.WriteTo(output, _repeated_playerPosition_codec);
    if (IsDead != false) {
      output.WriteRawTag(16);
      output.WriteBool(IsDead);
    }
    if (VitalHealth != 0UL) {
      output.WriteRawTag(24);
      output.WriteUInt64(VitalHealth);
    }
    if (GuardHealth != 0UL) {
      output.WriteRawTag(32);
      output.WriteUInt64(GuardHealth);
    }
    if (CurrentActionId != 0UL) {
      output.WriteRawTag(40);
      output.WriteUInt64(CurrentActionId);
    }
    if (CurrentActionFrame != 0UL) {
      output.WriteRawTag(48);
      output.WriteUInt64(CurrentActionFrame);
    }
    if (CurrentActionFrameCount != 0UL) {
      output.WriteRawTag(56);
      output.WriteUInt64(CurrentActionFrameCount);
    }
    if (IsActionEnd != false) {
      output.WriteRawTag(64);
      output.WriteBool(IsActionEnd);
    }
    if (IsAlwaysCancelable != false) {
      output.WriteRawTag(72);
      output.WriteBool(IsAlwaysCancelable);
    }
    if (CurrentActionHitCount != 0UL) {
      output.WriteRawTag(80);
      output.WriteUInt64(CurrentActionHitCount);
    }
    if (CurrentHitStunFrame != 0UL) {
      output.WriteRawTag(88);
      output.WriteUInt64(CurrentHitStunFrame);
    }
    if (IsInHitStun != false) {
      output.WriteRawTag(96);
      output.WriteBool(IsInHitStun);
    }
    if (SpriteShakePosition != 0UL) {
      output.WriteRawTag(104);
      output.WriteUInt64(SpriteShakePosition);
    }
    if (MaxSpriteShakeFrame != 0UL) {
      output.WriteRawTag(112);
      output.WriteUInt64(MaxSpriteShakeFrame);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    playerPosition_.WriteTo(ref output, _repeated_playerPosition_codec);
    if (IsDead != false) {
      output.WriteRawTag(16);
      output.WriteBool(IsDead);
    }
    if (VitalHealth != 0UL) {
      output.WriteRawTag(24);
      output.WriteUInt64(VitalHealth);
    }
    if (GuardHealth != 0UL) {
      output.WriteRawTag(32);
      output.WriteUInt64(GuardHealth);
    }
    if (CurrentActionId != 0UL) {
      output.WriteRawTag(40);
      output.WriteUInt64(CurrentActionId);
    }
    if (CurrentActionFrame != 0UL) {
      output.WriteRawTag(48);
      output.WriteUInt64(CurrentActionFrame);
    }
    if (CurrentActionFrameCount != 0UL) {
      output.WriteRawTag(56);
      output.WriteUInt64(CurrentActionFrameCount);
    }
    if (IsActionEnd != false) {
      output.WriteRawTag(64);
      output.WriteBool(IsActionEnd);
    }
    if (IsAlwaysCancelable != false) {
      output.WriteRawTag(72);
      output.WriteBool(IsAlwaysCancelable);
    }
    if (CurrentActionHitCount != 0UL) {
      output.WriteRawTag(80);
      output.WriteUInt64(CurrentActionHitCount);
    }
    if (CurrentHitStunFrame != 0UL) {
      output.WriteRawTag(88);
      output.WriteUInt64(CurrentHitStunFrame);
    }
    if (IsInHitStun != false) {
      output.WriteRawTag(96);
      output.WriteBool(IsInHitStun);
    }
    if (SpriteShakePosition != 0UL) {
      output.WriteRawTag(104);
      output.WriteUInt64(SpriteShakePosition);
    }
    if (MaxSpriteShakeFrame != 0UL) {
      output.WriteRawTag(112);
      output.WriteUInt64(MaxSpriteShakeFrame);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += playerPosition_.CalculateSize(_repeated_playerPosition_codec);
    if (IsDead != false) {
      size += 1 + 1;
    }
    if (VitalHealth != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(VitalHealth);
    }
    if (GuardHealth != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(GuardHealth);
    }
    if (CurrentActionId != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CurrentActionId);
    }
    if (CurrentActionFrame != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CurrentActionFrame);
    }
    if (CurrentActionFrameCount != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CurrentActionFrameCount);
    }
    if (IsActionEnd != false) {
      size += 1 + 1;
    }
    if (IsAlwaysCancelable != false) {
      size += 1 + 1;
    }
    if (CurrentActionHitCount != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CurrentActionHitCount);
    }
    if (CurrentHitStunFrame != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CurrentHitStunFrame);
    }
    if (IsInHitStun != false) {
      size += 1 + 1;
    }
    if (SpriteShakePosition != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SpriteShakePosition);
    }
    if (MaxSpriteShakeFrame != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MaxSpriteShakeFrame);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PlayerState other) {
    if (other == null) {
      return;
    }
    playerPosition_.Add(other.playerPosition_);
    if (other.IsDead != false) {
      IsDead = other.IsDead;
    }
    if (other.VitalHealth != 0UL) {
      VitalHealth = other.VitalHealth;
    }
    if (other.GuardHealth != 0UL) {
      GuardHealth = other.GuardHealth;
    }
    if (other.CurrentActionId != 0UL) {
      CurrentActionId = other.CurrentActionId;
    }
    if (other.CurrentActionFrame != 0UL) {
      CurrentActionFrame = other.CurrentActionFrame;
    }
    if (other.CurrentActionFrameCount != 0UL) {
      CurrentActionFrameCount = other.CurrentActionFrameCount;
    }
    if (other.IsActionEnd != false) {
      IsActionEnd = other.IsActionEnd;
    }
    if (other.IsAlwaysCancelable != false) {
      IsAlwaysCancelable = other.IsAlwaysCancelable;
    }
    if (other.CurrentActionHitCount != 0UL) {
      CurrentActionHitCount = other.CurrentActionHitCount;
    }
    if (other.CurrentHitStunFrame != 0UL) {
      CurrentHitStunFrame = other.CurrentHitStunFrame;
    }
    if (other.IsInHitStun != false) {
      IsInHitStun = other.IsInHitStun;
    }
    if (other.SpriteShakePosition != 0UL) {
      SpriteShakePosition = other.SpriteShakePosition;
    }
    if (other.MaxSpriteShakeFrame != 0UL) {
      MaxSpriteShakeFrame = other.MaxSpriteShakeFrame;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10:
        case 8: {
          playerPosition_.AddEntriesFrom(input, _repeated_playerPosition_codec);
          break;
        }
        case 16: {
          IsDead = input.ReadBool();
          break;
        }
        case 24: {
          VitalHealth = input.ReadUInt64();
          break;
        }
        case 32: {
          GuardHealth = input.ReadUInt64();
          break;
        }
        case 40: {
          CurrentActionId = input.ReadUInt64();
          break;
        }
        case 48: {
          CurrentActionFrame = input.ReadUInt64();
          break;
        }
        case 56: {
          CurrentActionFrameCount = input.ReadUInt64();
          break;
        }
        case 64: {
          IsActionEnd = input.ReadBool();
          break;
        }
        case 72: {
          IsAlwaysCancelable = input.ReadBool();
          break;
        }
        case 80: {
          CurrentActionHitCount = input.ReadUInt64();
          break;
        }
        case 88: {
          CurrentHitStunFrame = input.ReadUInt64();
          break;
        }
        case 96: {
          IsInHitStun = input.ReadBool();
          break;
        }
        case 104: {
          SpriteShakePosition = input.ReadUInt64();
          break;
        }
        case 112: {
          MaxSpriteShakeFrame = input.ReadUInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10:
        case 8: {
          playerPosition_.AddEntriesFrom(ref input, _repeated_playerPosition_codec);
          break;
        }
        case 16: {
          IsDead = input.ReadBool();
          break;
        }
        case 24: {
          VitalHealth = input.ReadUInt64();
          break;
        }
        case 32: {
          GuardHealth = input.ReadUInt64();
          break;
        }
        case 40: {
          CurrentActionId = input.ReadUInt64();
          break;
        }
        case 48: {
          CurrentActionFrame = input.ReadUInt64();
          break;
        }
        case 56: {
          CurrentActionFrameCount = input.ReadUInt64();
          break;
        }
        case 64: {
          IsActionEnd = input.ReadBool();
          break;
        }
        case 72: {
          IsAlwaysCancelable = input.ReadBool();
          break;
        }
        case 80: {
          CurrentActionHitCount = input.ReadUInt64();
          break;
        }
        case 88: {
          CurrentHitStunFrame = input.ReadUInt64();
          break;
        }
        case 96: {
          IsInHitStun = input.ReadBool();
          break;
        }
        case 104: {
          SpriteShakePosition = input.ReadUInt64();
          break;
        }
        case 112: {
          MaxSpriteShakeFrame = input.ReadUInt64();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class GameState : pb::IMessage<GameState>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GameState> _parser = new pb::MessageParser<GameState>(() => new GameState());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GameState> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FootsiesServiceReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GameState() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GameState(GameState other) : this() {
    player0_ = other.player0_ != null ? other.player0_.Clone() : null;
    player1_ = other.player1_ != null ? other.player1_.Clone() : null;
    terminated_ = other.terminated_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GameState Clone() {
    return new GameState(this);
  }

  /// <summary>Field number for the "player0" field.</summary>
  public const int Player0FieldNumber = 1;
  private global::PlayerState player0_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::PlayerState Player0 {
    get { return player0_; }
    set {
      player0_ = value;
    }
  }

  /// <summary>Field number for the "player1" field.</summary>
  public const int Player1FieldNumber = 2;
  private global::PlayerState player1_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::PlayerState Player1 {
    get { return player1_; }
    set {
      player1_ = value;
    }
  }

  /// <summary>Field number for the "terminated" field.</summary>
  public const int TerminatedFieldNumber = 3;
  private bool terminated_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Terminated {
    get { return terminated_; }
    set {
      terminated_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GameState);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GameState other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Player0, other.Player0)) return false;
    if (!object.Equals(Player1, other.Player1)) return false;
    if (Terminated != other.Terminated) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (player0_ != null) hash ^= Player0.GetHashCode();
    if (player1_ != null) hash ^= Player1.GetHashCode();
    if (Terminated != false) hash ^= Terminated.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (player0_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Player0);
    }
    if (player1_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Player1);
    }
    if (Terminated != false) {
      output.WriteRawTag(24);
      output.WriteBool(Terminated);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (player0_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Player0);
    }
    if (player1_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Player1);
    }
    if (Terminated != false) {
      output.WriteRawTag(24);
      output.WriteBool(Terminated);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (player0_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Player0);
    }
    if (player1_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Player1);
    }
    if (Terminated != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GameState other) {
    if (other == null) {
      return;
    }
    if (other.player0_ != null) {
      if (player0_ == null) {
        Player0 = new global::PlayerState();
      }
      Player0.MergeFrom(other.Player0);
    }
    if (other.player1_ != null) {
      if (player1_ == null) {
        Player1 = new global::PlayerState();
      }
      Player1.MergeFrom(other.Player1);
    }
    if (other.Terminated != false) {
      Terminated = other.Terminated;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (player0_ == null) {
            Player0 = new global::PlayerState();
          }
          input.ReadMessage(Player0);
          break;
        }
        case 18: {
          if (player1_ == null) {
            Player1 = new global::PlayerState();
          }
          input.ReadMessage(Player1);
          break;
        }
        case 24: {
          Terminated = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (player0_ == null) {
            Player0 = new global::PlayerState();
          }
          input.ReadMessage(Player0);
          break;
        }
        case 18: {
          if (player1_ == null) {
            Player1 = new global::PlayerState();
          }
          input.ReadMessage(Player1);
          break;
        }
        case 24: {
          Terminated = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Empty : pb::IMessage<Empty>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Empty> _parser = new pb::MessageParser<Empty>(() => new Empty());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Empty> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FootsiesServiceReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Empty() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Empty(Empty other) : this() {
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Empty Clone() {
    return new Empty(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Empty);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Empty other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Empty other) {
    if (other == null) {
      return;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
